<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>ExpenseManager.Services</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\ExpenseManager.Data\ExpenseManager.Data.csproj" />
		<ProjectReference Include="..\ExpenseManager.Domain\ExpenseManager.Domain.csproj" />
	</ItemGroup>
</Project>